### PR TITLE
Fix tests

### LINKED ISSUE #851: All the Travis builds are broken...
Every new pull request fails due to stylecheck failures in existing code.

### PR DESCRIPTION
**Pull request by remram44**
Fix #851

### CODE REVIEW

**Comment by remram44** [comment]
Tests on Python 3 still fail because the "unicode" symbol appears in some files.

**Comment by mitsuhiko** [comment]
This introduces a bug by changing `__unicode__` to `__str__`.

**Comment by remram44** [comment]
I'm using [`implements_to_string()`](https://github.com/mitsuhiko/werkzeug/blob/34d6ab9dee2b819e6243f9fdfe28fab71fad0c89/werkzeug/_compat.py#L53), which means this `__str__` is actually `__unicode__` on PY2 and `__str__` gets implemented as `__unicode__().encode('utf-8')`

I may have missed something, I'll double-check ;)

**Comment by mitsuhiko** [comment]
Ah. Then you can open a new pull for this separately. I fixed the tests for now.

**Comment by remram44** [comment]
Sure thing! I'm just waiting for the tests for master to complete, I'll resubmit shortly.

**Pull request closed without merging**
