### PR TITLE
Fix parse_options_header to handle RFC2616

### LINKED ISSUE #404: parse_options_header fails to parse quoted values
```python
header = '''multipart/form-data; boundary=----WebKitFormBoundaryUv6L4qL9bQlBDkzK
form-data; name="αυτό είναι, ένα αρχείο με Ϋ διαλυτικά ;.rtf"; filename="αυτό είναι, ένα αρχείο με Ϋ διαλυτικά ;.rtf"
application/msword''' 
print parse_options_header(header)[1]["filename"]
```
Given the above code the output should be :
```text
αυτό είναι, ένα αρχείο με Ϋ διαλυτικά ;
```
without any quotes, and with a final semicolon. Instead it is:
```text
"αυτό είναι, ένα αρχείο με Ϋ διαλυτικά
```

### PR DESCRIPTION
**Pull request by jd**
The current version of the function does not handle correctly the
multiple MIME type version of the header as described in RFC2616. This
patches fixes that. It also fixes #404 at the same time.

### CODE REVIEW

**Comment by jd** [comment]
I've just updated it to latest master, would be nice to merge this now :)

**Comment by untitaker** [comment]
Are you using this function directly in your code, or is this for some other part of Werkzeug?

**Comment by jd** [comment]
This is only used in my code for now, but it's likely the rest of werkzeug could be updated to leverage that in a later patch.

**Comment by jd** [comment]
@untitaker I've just updated it, it would be nice to merge now :(

**Comment by untitaker** [comment]
Merged, thanks!

**Comment by jd** [comment]
:+1: @untitaker

**Pull request merged**
