### PR TITLE
Add test_requires entry containing pytest, requests

### PR DESCRIPTION
**Pull request by djc**
This helps package maintainers to track dependencies.

### CODE REVIEW

**Comment by untitaker** [comment]
We already have the tox.ini for this though. I'm not a great fan of duplicating this information.

**Comment by djc** [comment]
Fair enough.

**Comment by untitaker** [comment]
Just to clarify, does that cover your usecase? How would you use the above patch?

**Comment by djc** [comment]
Mostly for manual checking if there are any new dependencies required on a version bump. I.e. in werkzeug-0.10 there's a new requests dependency for running the tests.

**Pull request closed without merging**
