### PR TITLE
Optional curl-like verbose logging

### PR DESCRIPTION
**Pull request by jjdenis**
Hello!

I needed more verbose logging, as can be seen here https://github.com/jjdenis/eve-restangular-demo and here: http://librelist.com/browser//flask/2015/3/14/show-full-http-request-and-response-on-console/

So I fiddled with serving.py, and I got logging messages like this:

127.0.0.1 - - [15/Mar/2015 13:54:01] 
< GET / HTTP/1.1
< User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8| zlib/1.2.5
< Host: 127.0.0.1:5000
< Accept: */*
< 

> 200 -

Just what I needed! I added another option to run_simple, and added a global variable.

I would like to see the rest of the message, but I still haven't figured out how to.

See if you like it.

### CODE REVIEW

**Comment by untitaker** [comment]
I'd recommend implementing this as a middleware instead.

**Comment by jjdenis** [comment]
I think full curl-like logging capabilities would enhance the Flask-Werkzeug experience for newbies like me. Any Flask app development would be easier, and Flask could be used as a kind of reversed curl, in order to learn http.

David Nieder showed me how to log in flask, http://librelist.com/browser//flask/2015/3/14/show-full-http-request-and-response-on-console/#ce614ed2978c19925769f5366565184b. And it works like a charm. But I guess precise logging should better achieved in the server itself.

**Comment by RonnyPfannschmidt** [comment]
can we close this pr?

while the idea is nice the implementation using globals
and not having tests cannot be accepted as is

and given the example on the mailinglist i suspect this approach is no longer necessary to begin with

the perfect place might indeed be a middleware (then it would work for any wsgi application)
i suspect something like that also exists

**Comment by jjdenis** [comment]
No problem with me: it was just an idea, not intended for merging.

**Pull request closed without merging**
