### PR TITLE
Avoid Sha1

### PR DESCRIPTION
**Pull request by R5spS3c**
According to the latest news about sha1, this hashing algorithm should be avoided.

### CODE REVIEW

**Comment by remram44** [comment]
This looks harmless but perhaps you could update the test? ([test_password_hashing](https://github.com/mitsuhiko/werkzeug/blob/d9e7736de41e7cbf5de70a15e28449b4dd4adab0/tests/test_security.py#L26-L29))

**Comment by DasIch** [comment]
Can you link to a reputable source(s) for the claim that sha1 shouldn't be used in general and in this particular context? Additionally not using sha1 is one thing, using something else is another. Why should sha384 be chosen instead?

**Comment by untitaker** [comment]
In general see https://sites.google.com/site/itstheshappening/, but not sure about combination with PBKDF2. Can't harm though.

**Comment by remram44** [comment]
To this day, SHA-3 is supposed to be secure; there have been publications about weaknesses in SHA-1, although nothing practical came out of it so far (that we know of).

I don't think it is an issue when used in PBKDF2 though (see [this SO question](http://stackoverflow.com/questions/4938906/is-sha1-still-secure-for-use-as-hash-function-in-pbkdf2)).

**Comment by R5spS3c** [comment]
I thought when it is possible to use a more secure hashing algorithm, why should I use an old one and wait until it's totally broken.

**Comment by DasIch** [comment]
@remram44 sha384 is *not* sha-3, it's just sha-2 with 384bits of output.

**Comment by mitsuhiko** [comment]
I already wrote in the other post -1 on changing this. First of all because this is for password hashing and not cert security / integrity, secondly because we're not using SHA1 for a long time, we're using PBKDF2 or HMAC-SHA1. Even HMAC-MD5 is at present unbroken so what happens to SHA1 by itself, has little to do with what we are doing here.

**Comment by R5spS3c** [comment]
I thought it's no big deal to change one line to increase the security, but it seems I'm wrong

**Comment by remram44** [comment]
You are right, but this doesn't improve security.

**Comment by mitsuhiko** [comment]
That's not how security works.  You need to understand what you are changing and why.  Changing one SHA based algorithm for another (less used) SHA algorithm which also increases the storage requirement is a major change that needs consideration.  This for instance could immediately mean that people's application break on upgrading because the field now is longer.  So there need to be good reason for doing it, and from where I'm standing, changing SHA1 to another from the same family has no security benefits if it's behind HMAC or PBKDF based hashing.

(Let alone that even if SHA1 was indeed completely hacked, it would require knowledge of the hash to create a collision.  This is not what an attack for passwords looks like.  What password hashing wants to avoid is to increase the computational complexity for the case where someone runs away with your password database and does an offline rainbow table / brute force attack and then use the passwords on other websites.  We protect against that with PBKDF and not with SHA.)

**Pull request closed without merging**
